component_management:
  default_rules:
    paths:
      - "intent_kit/**"
    statuses:
      project:
        target: auto
        threshold: 5%
        base: auto
      patch:
        target: auto
        threshold: 5%
        base: auto
  individual_components:
    - component_id: core_engine
      name: Core Engine (Framework & Intent Graph)
      paths:
        - "intent_kit/graph/**"
        - "intent_kit/nodes/**"
      statuses:
        project:
          target: auto
          threshold: 5%
          base: auto
        patch:
          target: auto
          threshold: 5%
          base: auto
    - component_id: node_library
      name: Node Library (Batteries Included)
      paths:
        - "intent_kit/node_library/**"
      statuses:
        project:
          target: auto
          threshold: 5%
          base: auto
        patch:
          target: auto
          threshold: 5%
          base: auto
    - component_id: llm_services
      name: LLM Services & Model Clients
      paths:
        - "intent_kit/services/ai/**"
        - "intent_kit/services/yaml_service.py"
      statuses:
        project:
          target: auto
          threshold: 5%
          base: auto
        patch:
          target: auto
          threshold: 5%
          base: auto
    - component_id: eval_framework
      name: Evaluation Framework
      paths:
        - "intent_kit/evals/**"
      statuses:
        project:
          target: auto
          threshold: 5%
          base: auto
        patch:
          target: auto
          threshold: 5%
          base: auto
    - component_id: context_management
      name: Context Management
      paths:
        - "intent_kit/context/**"
      statuses:
        project:
          target: auto
          threshold: 5%
          base: auto
        patch:
          target: auto
          threshold: 5%
          base: auto
    - component_id: utils
      name: Utilities & Shared Logic
      paths:
        - "intent_kit/utils/**"
        - "intent_kit/types.py"
      statuses:
        project:
          target: auto
          threshold: 5%
          base: auto
        patch:
          target: auto
          threshold: 5%
          base: auto
    - component_id: error_handling
      name: Error Handling
      paths:
        - "intent_kit/exceptions/**"
      statuses:
        project:
          target: auto
          threshold: 5%
          base: auto
        patch:
          target: auto
          threshold: 5%
          base: auto
