site_name: intent-kit
site_description: Open-source Python framework for intent classification and execution
site_url: https://intent-kit.github.io
repo_url: https://github.com/intent-kit/intent-kit

theme:
  name: material

plugins:
  - search
  - mkdocstrings
  - literate-nav

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - API Reference:
      - intent_kit: api_reference.md
  - Examples:
      - Calculator Bot: examples/calculator-bot.md