# LLM Configuration for Intent Kit Evaluations
# Replace the API keys with your actual keys

openai:
  api_key: "your-openai-api-key-here"
  model: "gpt-3.5-turbo"
  max_tokens: 100

anthropic:
  api_key: "your-anthropic-api-key-here"
  model: "claude-3-sonnet-20240229"
  max_tokens: 100

google:
  api_key: "your-google-api-key-here"
  model: "gemini-pro"
  max_tokens: 100

ollama:
  api_key: ""  # Ollama doesn't require API key
  model: "llama2"
  base_url: "http://localhost:11434"
  max_tokens: 100

# You can also set API keys via environment variables:
# OPENAI_API_KEY=your-key
# ANTHROPIC_API_KEY=your-key
# GOOGLE_API_KEY=your-key 