name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install .[dev] ruff mypy build

      - name: Lint (ruff)
        run: |
          ruff check .

      - name: Type check (mypy)
        run: |
          mypy intent_kit tests || true  # allow gradual typing; remove '|| true' when clean

      - name: Run tests
        run: |
          pytest -q

      - name: Build package
        run: |
          python -m build --sdist --wheel --outdir dist/

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: intent-kit-build
          path: dist/

  publish:
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # required for trusted publishing
    steps:
      - name: Download dist artefacts
        uses: actions/download-artifact@v4
        with:
          name: intent-kit-build
          path: dist

      # Publish to TestPyPI first for safety
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.8.8
        with:
          repository-url: https://test.pypi.org/legacy/
        env:
          PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}

      # Optionally publish to real PyPI if secret is present
      - name: Publish to PyPI
        if: secrets.PYPI_API_TOKEN != ''
        uses: pypa/gh-action-pypi-publish@v1.8.8
        with:
          skip-existing: true
        env:
          PASSWORD: ${{ secrets.PYPI_API_TOKEN }}