name: CI

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Sync dependencies
        run: uv sync --group dev
      - name: Lint (Ruff)
        run: uv run lint
      - name: Black
        run: uv run black --fix .
      - name: Typecheck (mypy)
        run: uv run typecheck

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Sync dependencies
        run: uv sync --group dev
      - name: Tests with coverage
        run: |
          uv run pytest --cov=intent_kit --cov-branch --cov-report=xml --cov-report=html
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true

  eval:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Sync dependencies
        run: uv sync --group dev
      - name: Evaluations (Mock Mode)
        run: uv run python -m intent_kit.evals.run_all_evals --quiet --mock

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Sync dependencies
        run: uv sync --group dev
      - name: Install pip-audit
        run: uv add --group dev pip-audit
      - name: Security audit
        run: uv run pip-audit --local

  build:
    runs-on: ubuntu-latest
    needs: [test, eval, security]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Build package
        run: uv build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-distributions
          path: dist
