name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install .[dev] ruff mypy build

      - name: Lint (ruff)
        run: |
          ruff check .

      - name: Type check (mypy)
        run: |
          mypy intent_kit tests || true  # allow gradual typing; remove '|| true' when clean

      - name: Run tests
        run: |
          pytest -q

      - name: Build package
        run: |
          python -m build --sdist --wheel --outdir dist/

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: intent-kit-build
          path: dist/